import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { getSetup2FA, confirmSetup2FA } from "../../services/api";

export default function TwoFactorSetup({ user, on2faSuccess }) {
  const navigate = useNavigate();
  const [code, setCode] = useState("");
  const [error, setError] = useState("");
  const [qrCode, setQrCode] = useState("");
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText("JBSW Y3DP EHPK 3PXP");
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  useEffect(() => {
    const fetchSetup = async () => {
      try {
        const res = await getSetup2FA();
        if (res.data?.data?.qr_code) {
          setQrCode(res.data.data.qr_code);
        }
      } catch (err) {
        setError("Failed to load 2FA setup details. Please log in again.");
      }
    };
    fetchSetup();
  }, []);

  const handleActivate = async (e) => {
    e.preventDefault();
    setError("");

    if (code.replace(/\s/g, "").length !== 6) {
      setError("Please enter a valid 6-digit verification code.");
      return;
    }

    try {
      await confirmSetup2FA(code);
      navigate("/login");
    } catch (err) {
      setError(err.response?.data?.message || err.message || "Failed to setup 2FA.");
    }
  };

  return (
    <div className="w-full flex-grow flex flex-col">
      {/* Main Content Canvas */}
      <main className="flex-grow flex items-center justify-center py-stack-lg px-margin-page">
        <div className="max-w-3xl w-full border border-outline bg-surface-container-lowest flex flex-col md:flex-row">
          {/* Left Panel: Instructions */}
          <div className="p-stack-lg md:w-1/2 border-b md:border-b-0 md:border-r border-outline flex flex-col justify-center bg-surface-container-low">
            <div className="mb-stack-lg">
              <span className="material-symbols-outlined text-display mb-stack-sm text-primary" style={{ fontSize: "48px" }}>
                security
              </span>
              <h1 className="font-headline-lg text-headline-lg text-primary mb-stack-sm font-semibold">
                Two-Factor Authentication Setup
              </h1>
              <p className="font-body-md text-body-md text-text-secondary">
                Secure your registeration by configuring an authenticator app. This is a mandatory requirement.
              </p>
            </div>
            <ol className="list-decimal list-inside space-y-stack-md font-body-md text-body-md text-text-primary">
              <li>Download a trusted authenticator app (e.g., Google Authenticator, Authy).</li>
              <li>Scan the QR code displayed on the right.</li>
              <li>Enter the 6-digit verification code generated by your app to verify the setup.</li>
            </ol>
          </div>

          {/* Right Panel: Execution */}
          <div className="p-stack-lg md:w-1/2 flex flex-col items-center justify-center bg-surface-container-lowest">
            {error && (
              <div className="w-full mb-4 p-3 bg-error-container border border-error text-error text-sm font-bold">
                {error}
              </div>
            )}

            {/* QR Code Area */}
            <div className="mb-stack-lg w-full flex flex-col items-center">
              <span className="font-label-lg text-label-lg text-primary mb-stack-sm uppercase tracking-tight w-full text-left">
                Scan Code
              </span>
              <div className="border-4 border-primary p-4 bg-white">
                {qrCode ? (
                  <img
                    className="w-48 h-48 object-cover"
                    alt="2FA QR Code"
                    src={qrCode}
                  />
                ) : (
                  <div className="w-48 h-48 flex items-center justify-center text-sm text-text-secondary">
                    Loading QR...
                  </div>
                )}
              </div>
            </div>

            {/* Manual Entry Fallback */}
            <div className="mb-stack-lg w-full">
              <span className="font-label-md text-label-md text-text-secondary mb-stack-sm block">
                Unable to scan? Use this setup key:
              </span>
              <div className="flex items-center justify-between border border-outline bg-surface-main p-3">
                <code className="font-body-md text-body-md text-primary tracking-widest select-all">
                  JBSW Y3DP EHPK 3PXP
                </code>
                <button
                  onClick={handleCopy}
                  className="text-secondary hover:text-primary transition-none ml-4 flex items-center"
                  title="Copy to clipboard"
                >
                  <span className="material-symbols-outlined">{copied ? "check" : "content_copy"}</span>
                </button>
              </div>
            </div>

            {/* Verification Input */}
            <div className="w-full">
              <form onSubmit={handleActivate}>
                <label className="font-label-lg text-label-lg text-primary mb-stack-sm block" htmlFor="verification_code">
                  Verify Configuration
                </label>
                <div className="flex space-x-gutter">
                  <input
                    className="w-full border border-outline bg-surface-container-lowest font-body-lg text-body-lg text-primary px-4 py-3 focus:outline-none focus:ring-1 focus:ring-primary rounded-none tracking-widest text-center"
                    id="verification_code"
                    maxlength="6"
                    placeholder="000000"
                    type="text"
                    value={code}
                    onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))}
                    required
                  />
                </div>
                <button
                  type="submit"
                  className="w-full bg-primary text-on-primary font-label-lg text-label-lg py-4 mt-stack-md hover:bg-on-primary-fixed-variant transition-none flex items-center justify-center rounded-none"
                >
                  <span className="material-symbols-outlined mr-2">check_circle</span>
                  Activate Security Key
                </button>
              </form>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
